### ISSUE TITLE
postgres

### ISSUE THREAD

**Issue by xdw15c** [kyob/LMSIncomePlugin#1]
nie dziala z postgresem

**Comment by kyob** [comment]
Już działa https://github.com/kyob/LMSIncomePlugin/commit/a49206f1aed097d2d57bd229374ec9012a394ed1

**Comment by xdw15c** [comment]
Zmieniles nazwy plikow, a stare zostaly.

**Comment by kyob** [comment]
Też, ale miałem wersje postgres u siebie, której nie wysłałem na publiczne repo.

**Comment by xdw15c** [comment]
mam na myśli to, że w repo są podwójnie pliki teraz

**Comment by kyob** [comment]
Fixed https://github.com/kyob/LMSIncomePlugin/commit/b9be3ef238db0b0824610a6a2fad10f5061b2e07 :)
